Autostart
stfalcon-studio/uaroads_ios pull request #6
Opened 2017-08-10 15:38 UTC by rybachenko2206

2017-08-14 12:22 UTC, alexz89ua commented on UARoads_swift/UARoads_swift.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.test.UARoads;
Ти походу робив тестову збірку та залишив тут не той бандл

2017-08-14 12:33 UTC, alexz89ua commented on UARoads_swift/UARoads_swift/Classes/Models/Managers/AutostartManager.swift
> +        if data.stationary == true {
Можливо тут краще застосувати switch case?

2017-08-14 12:34 UTC, alexz89ua commented on UARoads_swift/UARoads_swift/Classes/Models/Managers/AutostartManager.swift
> +        if mActivityType == .automotive || mActivityType == .cycling || mActivityType == .walking {
Нас цікавить тільки рух автомобілем

2017-08-14 12:38 UTC, alexz89ua requested changes
В цілому добре. Але мені потрібен білд та зверни увагу на мої коментарі.

2017-08-15 06:43 UTC, rybachenko2206 commented
я додав це для тестування, бо мені потрібно було пересвідчитись, що додаток працює (на реальному девайсі. Цей рядок відредагується

2017-08-15 06:52 UTC, rybachenko2206 commented on UARoads_swift/UARoads_swift/Classes/Models/Managers/AutostartManager.swift
> +        if data.stationary == true {
За цей випадок я навіть розказував, якщо пригадуєш: в CMMotionActivity ці значенння зроблені не як один параметер, а як список властивостей класу типу BOOL. 
var stationary: Bool
var walking: Bool
var running: Bool
.. так як тип руху не є виключно одним із -  можна отримати 2 з трьох параметрів  true. 
Тому я сам уже конвертую в enum, в свій, так би просто використав системний, а не писав стільки if-ів )

2017-08-15 06:55 UTC, rybachenko2206 commented on UARoads_swift/UARoads_swift.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.test.UARoads;
За це теж казав - так як я не маю доступу до apple.developer.account,  то збирав на свій. 
І оскільки  bundle Id має бути унікальним, то довелось змінити. Задам правильний, коли матиму змогу розсилати білд

2017-08-16 11:23 UTC, closed without merging